"""indexing 

Revision ID: fda258f6aab9
Revises: 4a61efb40865
Create Date: 2023-12-19 00:21:47.932496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda258f6aab9'
down_revision = '4a61efb40865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_artist_name'), ['artist_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_title'), ['title'], unique=False)

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_songs_artist_name'), ['artist_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_song_id'), ['song_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_songs_user_id'))
        batch_op.drop_index(batch_op.f('ix_songs_title'))
        batch_op.drop_index(batch_op.f('ix_songs_song_id'))
        batch_op.drop_index(batch_op.f('ix_songs_artist_name'))

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_title'))
        batch_op.drop_index(batch_op.f('ix_song_artist_name'))

    # ### end Alembic commands ###
