version: '3.7'
services:
  front:
    build: "frontend"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER=http://localhost:5000/graphql
      - REACT_APP_LOGINSERVER=http://localhost:3001
  web: 
    build: "myapp"
    ports: 
      - '5000:5000'
    image: chokhonelidze/backend:latest
    environment:
      - DB=mongodb://mongo:27017/app_development
      - APOLLO_KEY=service:Python-nrgjdu:••••••••••••••••••••••
      - APOLLO_GRAPH_REF=Python-nrgjdu@current
      - APOLLO_SCHEMA_REPORTING=true
    depends_on:
      - "postgres"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5438:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local