"""9.7.24 

Revision ID: bcb84e4668aa
Revises: eb0d0c2f839a
Create Date: 2024-09-07 18:15:19.307339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb84e4668aa'
down_revision = 'eb0d0c2f839a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('localLink', sa.String(length=1000), nullable=True))

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('localLink')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('localLink', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('localLink')

    # ### end Alembic commands ###
